import { SpacePreset } from './audioTypes';

export const SPACE_PRESETS: SpacePreset[] = [
  {
    id: 'studio-control',
    name: 'Control Room A',
    description: 'Treated reference acoustic studio. Controlled reflections with articulate stereo imaging.',
    acoustics: {
      width: 7,
      length: 9,
      height: 3.2,
      rt60: 0.35,
      damping: 12000,
      material: 'studio',
      earlyReflections: 0.45,
      preDelayMs: 12,
      wetMix: 0.22,
    },
    position: { x: 0, y: 2.5, z: 0.2 },
  },
  {
    id: 'scoring-hall',
    name: 'Symphonic Scoring Stage',
    description: 'Expansive hardwood orchestral hall. Lush harmonic envelopment and warm, rich decay.',
    acoustics: {
      width: 18,
      length: 28,
      height: 8.5,
      rt60: 2.3,
      damping: 6800,
      material: 'wood',
      earlyReflections: 0.72,
      preDelayMs: 32,
      wetMix: 0.42,
    },
    position: { x: -1.2, y: 5.5, z: 0.5 },
  },
  {
    id: 'gothic-cathedral',
    name: 'Gothic Cathedral',
    description: 'Massive vaulted stone sanctuary with continuous 5+ second diffuse acoustic wash.',
    acoustics: {
      width: 24,
      length: 42,
      height: 15,
      rt60: 5.6,
      damping: 3400,
      material: 'cathedral',
      earlyReflections: 0.85,
      preDelayMs: 65,
      wetMix: 0.65,
    },
    position: { x: 2.5, y: 8.0, z: 1.2 },
  },
  {
    id: 'concrete-silo',
    name: 'Concrete Industrial Vault',
    description: 'Unforgiving hard reflective bunker. Intense early specular reflections and dense resonant tail.',
    acoustics: {
      width: 12,
      length: 12,
      height: 14,
      rt60: 3.8,
      damping: 4800,
      material: 'concrete',
      earlyReflections: 0.92,
      preDelayMs: 20,
      wetMix: 0.5,
    },
    position: { x: -3.0, y: 4.0, z: -0.2 },
  },
  {
    id: 'ceramic-chamber',
    name: 'Vintage Ceramic Chamber',
    description: 'Bright, snappy physical tile echo chamber modeled after 1960s Abbey Road chambers.',
    acoustics: {
      width: 6.5,
      length: 8.0,
      height: 3.0,
      rt60: 1.6,
      damping: 9500,
      material: 'tile',
      earlyReflections: 0.8,
      preDelayMs: 18,
      wetMix: 0.38,
    },
    position: { x: 1.5, y: 3.0, z: 0 },
  },
  {
    id: 'anechoic-chamber',
    name: 'Anechoic Free-Field',
    description: 'Zero acoustic boundary reflections. Pure direct sound with 100% absorption on all planes.',
    acoustics: {
      width: 6,
      length: 6,
      height: 4,
      rt60: 0.08,
      damping: 18000,
      material: 'anechoic',
      earlyReflections: 0.02,
      preDelayMs: 0,
      wetMix: 0.05,
    },
    position: { x: 0, y: 2.0, z: 0 },
  },
];
